config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :restaurants do
      resources :reviews
    end
  end
  resources :restaurants, only: [ :index, :show, :new, :create ] do
    resources :reviews, only: [ :new, :create ]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"], allow_nil: false }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, inclusion: { in: (0..5)}, numericality: { only_integer: true }
end

app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [ :show, :edit, :update, :destroy ] # permet de ne pas répéter le code de set_restaurant
  def index
    @restaurants = Restaurant.all
  end

  def show
    # @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    # Restaurant.new(params[:restaurant]) # possible grâce au form_for mais dangereux
    @restaurant = Restaurant.new(restaurant_params) # strong params : limite les params qui seront stockés en DB
    if @restaurant.save
      redirect_to admin_restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def edit
    # @restaurant = Restaurant.find(params[:id])
  end

  def update
    # @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)
    @restaurant.save
    redirect_to admin_restaurant_path(@restaurant)
  end

  def destroy
    # @restaurant = Restaurant.find(params[:id])
    @restaurant.delete
    redirect_to admin_restaurants_path
  end

  private
  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < ApplicationController
  before_action :set_restaurant
  before_action :set_review, only: [ :destroy, :edit, :update ]
  def new
    @review = Review.new
  end

  def create
    @review = @restaurant.reviews.build(review_params)
    if @review.save
      redirect_to admin_restaurant_path(@restaurant)
    else
      render :new # renvoie au formulaire en cas d'erreur de validation
    end
  end

  def edit
  end

  def update
    @review.update(review_params)
    @review.save
    redirect_to admin_restaurant_path(@restaurant)
  end

  def destroy
    @review.delete
    redirect_to admin_restaurant_path(@restaurant)
  end

  private
  def review_params
    params.require(:review).permit(:content, :rating)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

   def set_review
    @review = Review.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_restaurant, only: [ :new, :create ]

  def new
    @review = Review.new
  end

  def create
    @review = @restaurant.reviews.build(review_params)
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new # renvoie au formulaire en cas d'erreur de validation
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
  def find_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/admin/restaurants/edit.html.erb
<div class="container padded">
  <%= simple_form_for @restaurant, url: admin_restaurant_path(@restaurant) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :name %>
      <%= f.input :address %>
      <%= f.input :phone_number %>
      <%= f.input :category, collection: ["chinese", "italian", "japanese", "french", "belgian"] %>
    </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  <% end %>
</div>

app/views/admin/restaurants/index.html.erb
<div class="container padded">
  <h1>Restaurants</h1>

  <%= link_to "Add a restaurant", new_admin_restaurant_path %>

  <ul>
    <% @restaurants.each do |resto| %>
      <h2><%= link_to resto.name, admin_restaurant_path(resto) %></h2>
    <% end %>
  </ul>
</div>

app/views/admin/restaurants/new.html.erb
<div class="container padded">
  <%= simple_form_for @restaurant, url: admin_restaurants_path do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :name %>
      <%= f.input :address %>
      <%= f.input :phone_number %>
      <%= f.input :category, collection: ["chinese", "italian", "japanese", "french", "belgian"] %>
    </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  <% end %>
</div>

app/views/admin/restaurants/show.html.erb
<div class="container padded">
  <p>
    <strong>Name:</strong>
    <%= @restaurant.name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= @restaurant.address %>
  </p>

  <p>
    <strong>Phone number:</strong>
    <%= @restaurant.phone_number %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= @restaurant.category %>
  </p>

  <p>
    <strong>Reviews:</strong>
    <% @restaurant.reviews.each do |review| %>
      <ul>
          <p><%= "*" * review.rating %></p>
          <p><%= review.content %></p>
          <%= link_to "Delete review", admin_restaurant_review_path(@restaurant, review), method: :delete %>
          <%= link_to "Edit review", edit_admin_restaurant_review_path(@restaurant, review) %>
      </ul>
    <% end %>
  </p>

  <%= link_to "Add a review", new_admin_restaurant_review_path(@restaurant) %>
  <%= link_to "Edit restaurant", edit_admin_restaurant_path(@restaurant) %>
  <%= link_to "Delete restaurant", admin_restaurant_path(@restaurant), method: :delete %>
  <%= link_to 'Back', admin_restaurants_path %>
</div>

app/views/admin/reviews/edit.html.erb
<div class="container padded">
  <h1>Edit this review for <%= @restaurant.name %></h1>
  <%= simple_form_for [@restaurant, @review], url: admin_restaurant_review_path(@restaurant, @review) do |f| %>
    <%= f.input :content %>
    <%= f.input :rating, collection: (0..5) %>
    <%= f.submit 'Add' %>
  <% end %>
</div>

app/views/admin/reviews/new.html.erb
<div class="container padded">
  <h1>Add a review for <%= @restaurant.name %></h1>
  <%= simple_form_for [@restautant, @review], url: admin_restaurant_reviews_path do |f| %>
    <%= f.input :content %>
    <%= f.input :rating, collection: (0..5) %>
    <%= f.submit 'Add' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= yield %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/restaurants/index.html.erb
<div class="container padded">
  <h1>Restaurants</h1>

  <%= link_to "Add a restaurant", new_restaurant_path %>

  <ul>
    <% @restaurants.each do |resto| %>
      <h2><%= link_to resto.name, restaurant_path(resto) %></h2>
    <% end %>
  </ul>
</div>

app/views/restaurants/new.html.erb
<div class="container padded">
  <%= simple_form_for(@restaurant) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :name %>
      <%= f.input :address %>
      <%= f.input :phone_number %>
      <%= f.input :category, collection: ["chinese", "italian", "japanese", "french", "belgian"] %>
    </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  <% end %>
</div>

app/views/restaurants/show.html.erb
<div class="container padded">
  <p>
    <strong>Name:</strong>
    <%= @restaurant.name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= @restaurant.address %>
  </p>

  <p>
    <strong>Phone number:</strong>
    <%= @restaurant.phone_number %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= @restaurant.category %>
  </p>



  <div class="reviews">
    <p>
      <strong>Reviews:</strong>
      <% @restaurant.reviews.each do |review| %>
        <ul>
            <p><%= "*" * review.rating %></p>
            <p><%= review.content %></p>
        </ul>
      <% end %>
    </p>
  </div>

  <%= link_to "Add a review", new_restaurant_review_path(@restaurant) %>
  <%= link_to 'Back', restaurants_path %>
</div>

app/views/reviews/new.html.erb
<div class="container padded">
  <h1>Add a review for <%= @restaurant.name %></h1>
  <%= simple_form_for [@restaurant, @review] do |f| %>
    <%= f.input :content %>
    <%= f.input :rating, collection: (0..5) %>
    <%= f.submit 'Add' %>
  <% end %>
</div>